version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      NEWS_API_SECRET: ${NEWS_API_SECRET}
      NEWS_API_URL: ${NEWS_API_URL}
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
